name: Terraform Drift Detection
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 
    
jobs:
  drift-check:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1"
    steps:
      - name: Pobranie kodu
        uses:  actions/checkout@v4
      - name: Konfig Terraforma
        uses:  hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.8.0'
      - name: Inicjalizacja
        run: terraform init
      - name: Planowanie
        run: terraform plan