name: Python Matrix CI
on:
  push:
    branches: 
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-ver: ["3.11", "3.12"]
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4
      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-ver}}
      - name: Weryfikacja
        run: |
          python --version