name: Cached Pipeline
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie repo
        uses: actions/checkout@v4
      - name: Konfig Pythona
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Instalacja zaleznosci
        run: |
          pip install -r requirements.txt
          echo "Testy zakonczone sukcesem"
