name: Terraform CI
on:
  pull_request:
    branches:
      - main
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1"
    steps:
      - name: Pobranie repo
        uses: actions/checkout@v4

      - name: Konfig Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Sprawdzanie formatowania
        run: terraform fmt -check

      - name: Inicjalizacja
        run: terraform init

      - name: Walidacja
        run: terraform validate

      - name: Plan
        run: terraform plan
