name: "Terraform setum and Format check"
description: "Instaluje terraforma i sprawdza formatowanie"

inputs:
  tf-version:
    required: false
    default: "1.8.0"

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf-version }}
    - name: Format check
      shell: bash
      run: terraform fmt -check
